name: Django Group Tests

on: [push, pull_request]

jobs:
  runtests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Run pylint
        run: |
          echo "Running pylint..."
          # Lint all Python files, ignore exit code to prevent pipeline crash
          pylint **/*.py || true

      - name: Run Django tests
        run: |
          echo "Running Django tests..."
          python manage.py test
