name: Hello, world    
on: [push]
jobs:
  hello:
    runs-on: ubuntu-latest  #runner
    steps:
      - name: Hello world
        run: echo "Hello, world!"






name:  Name 

on:
  push:
    branches:
      - main

jobs:
  print-name-job:
    runs-on: ubuntu-latest
    steps:
      - name: Name
        run: echo "My name is, kulabako!"